openapi: 3.0.0
info:
  title: Answer
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000/answers'
paths:
  '/{answerId}':
    parameters:
      - schema:
          type: string
        name: answerId
        in: path
        required: true
    get:
      summary: getAnswer
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  A:
                    type: string
                  B:
                    type: string
                  C:
                    type: string
                  D:
                    type: string
                  correctAnswer:
                    type: string
              examples: {}
        '400':
          description: Bad Request
        '':
          description: ''
      operationId: get-answers-answerId
      description: ''
      parameters: []
    post:
      summary: createAnswer
      operationId: post-answers-answerId
      responses:
        '201':
          description: '`Add answer ${answerId} successfully !!!`'
        '400':
          description: Bad Request
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                A:
                  type: string
                B:
                  type: string
                C:
                  type: string
                D:
                  type: string
                correctAnswer:
                  type: string
    patch:
      summary: updateAnswer
      operationId: patch-answers-answerId
      responses:
        '201':
          description: '`Update answer ${answerId} successfully !!!`'
        '400':
          description: Bad Request
      parameters:
        - schema:
            type: string
          in: query
          name: answerId
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                A:
                  type: string
                B:
                  type: string
                C:
                  type: string
                D:
                  type: string
                correctAnswer:
                  type: string
    delete:
      summary: deleteAnswer
      operationId: delete-answers-answerId
      responses:
        '200':
          description: '`Delete answer ${answerId} successfully !!!`'
        '400':
          description: Bad Request
      parameters:
        - schema:
            type: string
          in: query
          name: answerId
components:
  schemas: {}
