openapi: 3.0.0
info:
  title: Leaders
  version: '1.0'
servers:
  - url: 'https://enq-server.herokuapp.com/leaders'
paths:
  '/{leadersId}':
    parameters:
      - schema:
          type: string
        name: leadersId
        in: path
        required: true
    get:
      summary: getLeaders
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  userId:
                    type: array
                    items:
                      type: string
                  startAt:
                    type: string
                  endAt:
                    type: string
        '400':
          description: Bad Request
      operationId: get-leaders-leadersId
      parameters: []
    post:
      summary: createLeaders
      operationId: post-leaders-leadersId
      responses:
        '200':
          description: '`Add Leaders board ${data.id} Successfully !`'
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                userId:
                  type: array
                  items:
                    type: string
                startAt:
                  type: string
                endAt:
                  type: string
    patch:
      summary: updateLeaders
      operationId: patch-leaders-leadersId
      responses:
        '200':
          description: '`Update leaders ${leadersId} successfully !!!`'
        '400':
          description: Bad Request
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                userId:
                  type: array
                  items:
                    type: string
                startAt:
                  type: string
                endAt:
                  type: string
    delete:
      summary: deleteLeaders
      operationId: delete-leaders-leadersId
      responses:
        '200':
          description: '`Delete leaders ${leadersId} successfully !!!`'
        '400':
          description: Bad Request
      parameters:
        - schema:
            type: string
          in: query
          name: leadersId
          required: true
      description: ''
components:
  schemas: {}
