openapi: 3.0.0
info:
  title: Leaders
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/leaders/{leadersId}':
    parameters:
      - schema:
          type: string
        name: leadersId
        in: path
        required: true
    get:
      summary: getLeaders
      tags: []
      responses: {}
      operationId: get-leaders-leadersId
    post:
      summary: ''
      operationId: post-leaders-leadersId
      responses:
        '200':
          description: OK
    patch:
      summary: ''
      operationId: patch-leaders-leadersId
      responses:
        '200':
          description: OK
components:
  schemas: {}
