openapi: 3.0.0
info:
  title: Question
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/questions/{questionId}':
    parameters:
      - schema:
          type: string
        name: questionId
        in: path
        required: true
    get:
      summary: getQuestion
      tags: []
      responses: {}
      operationId: get-questions-questionId
    post:
      summary: addQuestion
      tags: []
      responses: {}
      operationId: post-questions-questionId
    patch:
      summary: ''
      operationId: patch-questions-questionId
      responses:
        '200':
          description: OK
    delete:
      summary: ''
      operationId: delete-questions-questionId
      responses:
        '200':
          description: OK
components:
  schemas: {}
