openapi: 3.0.0
info:
  title: TestExamHistory
  version: '1.0'
servers:
  - url: 'http://localhost:3000/test-exam-history'
paths:
  '/{testExamHistoryId}':
    parameters:
      - schema:
          type: string
        name: testExamHistoryId
        in: path
        required: true
    get:
      summary: getTestExamHistory
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  timeStart:
                    type: string
                  timeEnd:
                    type: string
                  testExamId:
                    type: string
                  answers:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad Request
      operationId: get-test-exam-history-testExamHistoryId
      parameters: []
    post:
      summary: addTestExamhistory
      tags: []
      responses:
        '200':
          description: '`Update test-exam-history ${testExamHistoryId} successfully !!!`'
        '400':
          description: Bad Request
      operationId: post-test-exam-history-testExamHistoryId
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                timeStart:
                  type: string
                timeEnd:
                  type: string
                testExamId:
                  type: string
                answers:
                  type: array
                  items:
                    type: string
    delete:
      summary: ''
      operationId: delete-test-exam-history-testExamHistoryId
      responses:
        '200':
          description: '`Delete test-exam-history ${testExamHistoryId} successfully !!!`'
        '400':
          description: Bad Request
      parameters:
        - schema:
            type: string
          in: query
          name: testExamHistoryId
      description: ''
    patch:
      summary: ''
      operationId: patch-testExamHistoryId
      responses:
        '200':
          description: '`Update test-exam-history ${testExamHistoryId} successfully !!!`'
        '400':
          description: Bad Request
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                timeStart:
                  type: string
                timeEnd:
                  type: string
                testExamId:
                  type: string
                answers:
                  type: array
                  items:
                    type: string
components:
  schemas: {}
