openapi: 3.0.0
info:
  title: TestExam
  version: '1.0'
servers:
  - url: 'https://enq-server.herokuapp.com//test-exam'
paths:
  '/{testExamId}':
    parameters:
      - schema:
          type: string
        name: testExamId
        in: path
        required: true
    get:
      summary: getTestExam
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  type:
                    type: string
                  rank:
                    type: string
                  questions:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad Request
      operationId: get-test-exam-testExamId
      parameters: []
    post:
      summary: createTestExam
      operationId: post-test-exam-testExamId
      responses:
        '200':
          description: '`Add test exam ${testExamId} successfully !!!`'
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                type:
                  type: string
                rank:
                  type: string
                questions:
                  type: array
                  items:
                    type: string
        description: ''
    patch:
      summary: updateTestExam
      operationId: patch-test-exam-testExamId
      responses:
        '200':
          description: '`Update test exam ${testExamId} successfully !!!`'
        '400':
          description: Bad Request
      parameters: []
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                type:
                  type: string
                rank:
                  type: string
                questions:
                  type: array
                  items:
                    type: string
    delete:
      summary: deleteTestExam
      operationId: delete-test-exam-testExamId
      responses:
        '200':
          description: '`Delete test exam ${testExamId} successfully !!!`'
        '400':
          description: Bad Request
      parameters: []
      description: ''
components:
  schemas: {}
